"""add initial resume and timestamps to user table

Revision ID: 43cef04e082e
Revises: 75c11c42fa6a
Create Date: 2025-06-18 15:51:14.521439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '43cef04e082e'
down_revision: Union[str, None] = '75c11c42fa6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('initial_resume', sa.JSON(), nullable=True), schema='auth')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True), schema='auth')
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True), schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at', schema='auth')
    op.drop_column('user', 'created_at', schema='auth')
    op.drop_column('user', 'initial_resume', schema='auth')
    # ### end Alembic commands ###
