"""added cover letter to job aplications table

Revision ID: 4b8144bd3605
Revises: e1f3857869ab
Create Date: 2025-08-22 13:05:35.428985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4b8144bd3605'
down_revision: Union[str, None] = 'e1f3857869ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('generated_cover_letter', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'generated_cover_letter', schema='app')
    # ### end Alembic commands ###
