"""update job application status to be string instead of enum

Revision ID: e1f3857869ab
Revises: 21897c6061c7
Create Date: 2025-08-19 14:28:11.319155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e1f3857869ab'
down_revision: Union[str, None] = '21897c6061c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_applications', 'resume_generation_status',
               existing_type=postgresql.ENUM('STARTED', 'PROCESSING_COMPANY_PROFILE', 'PROCESSING_RESUME_GENERATION', 'COMPLETED', 'FAILED', name='resumegenerationstatus'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True,
               schema='app')
    sa.Enum('STARTED', 'PROCESSING_COMPANY_PROFILE', 'PROCESSING_RESUME_GENERATION', 'COMPLETED', 'FAILED', name='resumegenerationstatus').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('STARTED', 'PROCESSING_COMPANY_PROFILE', 'PROCESSING_RESUME_GENERATION', 'COMPLETED', 'FAILED', name='resumegenerationstatus').create(op.get_bind())
    op.alter_column('job_applications', 'resume_generation_status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('STARTED', 'PROCESSING_COMPANY_PROFILE', 'PROCESSING_RESUME_GENERATION', 'COMPLETED', 'FAILED', name='resumegenerationstatus'),
               existing_nullable=True,
               schema='app')
    # ### end Alembic commands ###
